const Dict = {
    LEVEL: [
        {name: "SSS", key: "SSS"},
        {name: "SS", key: "SS"},
        {name: "S", key: "S"},
        {name: "AAA", key: "AAA"},
        {name: "AA", key: "AA"},
        {name: "A", key: "A"},
        {name: "蓝", key: "蓝"},
        {name: "绿", key: "绿"},
    ],
    TAG: [
        {name: "黑蝌蚪", key: "黑蝌蚪"},
        {name: "白蝌蚪", key: "白蝌蚪"},
        {name: "蘑菇", key: "蘑菇"},
        {name: "神奇蘑菇", key: "神奇蘑菇"},
        {name: "探索加速", key: "探索加速"},
        {name: "时间宝箱碎片概率", key: "时间宝箱碎片概率"},
        {name: "木材", key: "木材"},
        {name: "石材", key: "石材"},
        {name: "探索移动速度", key: "探索移动速度"},
        {name: "供奉速度", key: "供奉速度"},
        {name: "情报点", key: "情报点"},
        {name: "炼金试剂", key: "炼金试剂"},
        {name: "供奉宝箱增加", key: "供奉宝箱增加"},
        {name: "魔神宝箱增加", key: "魔神宝箱增加"},
        {name: "勋章产量增加", key: "勋章产量增加"},
        {name: "勋章消耗降低", key: "勋章消耗降低"},
        {name: "攻击", key: "攻击"},
        {name: "追击", key: "追击"},
        {name: "防御", key: "防御"},
        {name: "生命", key: "生命"},
        {name: "基因加速", key: "基因加速"},
        {name: "克隆加速", key: "克隆加速"},
        {name: "探索获得更多卡片", key: "探索获得更多卡片"},
        {name: "劳务派遣加速", key: "劳务派遣加速"},
        {name: "兵种上阵", key: "兵种上阵"},
        {name: "魔神细胞", key: "魔神细胞"},
        {name: "置于扶桑博物馆", key: "置于扶桑博物馆"},
        {name: "置于高丽博物馆", key: "置于高丽博物馆"},
        {name: "置于华夏博物馆", key: "置于华夏博物馆"},
        {name: "置于米国博物馆", key: "置于米国博物馆"},
        {name: "置于英伦博物馆", key: "置于英伦博物馆"},
        {name: "置于希域博物馆", key: "置于希域博物馆"},
        {name: "置于埃罗博物馆", key: "置于埃罗博物馆"},
        {name: "置于天竺博物馆", key: "置于天竺博物馆"},
        {name: "置于蝌蚪池", key: "置于蝌蚪池"},
        {name: "置于时光机", key: "置于时光机"},
        {name: "置于蘑菇园", key: "置于蘑菇园"},
        {name: "置于石材工坊", key: "置于石材工坊"},
        {name: "置于木材工坊", key: "置于木材工坊"},
        {name: "置于基因模拟装置", key: "置于基因模拟装置"},
        {name: "置于探索罗盘", key: "置于探索罗盘"},
        {name: "暴击", key: "暴击"},
    ],
    PREFER: [
        {name: "人气", key: "t1"},
        {name: "艺术", key: "t2"},
        {name: "信仰", key: "t3"},
        {name: "文化", key: "t4"},
        {name: "科技", key: "t5"},
    ]
}
export default Dict